apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry


resources:
- collector-agent.yaml
- collector-java.yaml
- Instrumentation.yml
- collector-gateway.yaml
- IngressRoute.yaml

helmCharts:
  - name: opentelemetry-helm-charts
    repo: https://open-telemetry.github.io
    releaseName: opentelemetry-operator
    namespace: opentelemetry
    version: 0.110.0
    valuesFile: opentelemetry-operator-0.110.0-values.yaml
