apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cwx

images:
- name: harbor.chenwx.top/chenwx/test-springweb
  newTag: "latest"

resources:
  - deployment.yaml
  - service.yaml
  - gateway.yaml
