apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cwx

images:
- name: harbor.chenwx.top/chenwx/web5
  newTag: "202605131651"

resources:
- secret-crypto.yaml
- deployment.yaml
- service.yaml
# - ingress.yaml
- gateway.yaml

configMapGenerator:
- files:
  - config/config.yaml
  name: web5-config
