---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: web5-secret
  namespace: cwx
spec:
  encryptedData:
    APP_DB_DSN: AgA/ijSlGFa0FXn9EmY6pnm1MqFMVzpQ/cgeNUij/W4IWC5nnaOpfS+0CDPvX9wbzYj9rgV+nS3NaOeOyT/W6x5TJWjJxGjzXFeuUZ+f9oh5KA8NdhbLFzd2CGLHMEJjrLPSv0hCW9X1vCxh5OP7E5j/kP0OLC7NCDoG81D7qKvO3wu/Wx21SeDwO/JJgZCHonxb+eIJrimyq/g+7KmPHZwVjS/Qs9z5P166fN0nU5l1pB9cchC1dWi2EC3RbPllHyZmylQERU6Kx7/EUkP0bB+K2L0hIPGBvBE4D8VPz58kVGbDTgPwHzjvC/R4S6v2L63DulHWj7GVHjfj4uwe40dKhYb3X9K5gDrBisJmY6fzFSVAf7q1cqvKlBJIwxhpuSxPuzzE7vr5TJU0bV9Qn3re2vK9BbZ/9DE2PyiIAE4PhEhbnk7ayFHvLcql5vcC6zPqxaRZFxftUVX6zcC7DKXVtboL1S77PdtqHVFgHxFZNHPoMZ5VhOVYrriEHXWXnjrElG1LEfu9B3cTEDB2JByRQMl2xqN8irKxdeAgioPbcTn7IFqXM+3w8sPZah9+tp99VjaKbbW9Y2Ca4Gqy9pxPlXlDHoUNyDRusXnjPZ0dSspgUp7whb+saMckfvMbsJ1e97Zx7UL4/Bnb+nrMiCCW7CvN9GD9VPl39abeQZol3jzpTd2/uB5Q0pQvX6Rwpqh7d071+5EIZsiaUsx8xmrlQO0kWw5ze4NkG8IWP7LTzxWXiHm5g+cw3i9/7EoQv3Ch3MMIB9K4Vm9r9aOZ8PljiYf0t6OIgf/psd80vtLEf72VtZhw3jHUa26Plps3GVjH4A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: web5-secret
      namespace: cwx
    type: Opaque
