apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cwx

images:
- name: harbor.chenwx.top/chenwx/web4
  newTag: "202605131955"

replicas:
- name: web4
  count: 1

resources:
  - deployment.yaml
  - service.yaml
  # - ingress.yaml
  - gateway.yaml
  - hpa.yaml
  - secret-crypto.yaml

configMapGenerator:
  - name: web4-config
    files:
      - config/config.yaml
