---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: web4-secret
  namespace: cwx
spec:
  encryptedData:
    APP_DB_DSN: AgB5gZCrh5IS8a6Aw+4R7sJov/rn2KU7ieDV9f1pngZEugAdsYzTbn0AQfi7jte2ZsKe9WaHxLjzEz+XjJZjq7TItt7r4Bg18hQAvRaaq45aHeuqgpsmHyjQXvi4w6RPSAY0dk4KLX31OOB2UFOO6MPnBGMVD5NFLqQd2Jt07lGAid2LxMw7EcVZWFLu1YDrET0T1u3G9g67whKf3ZEmSp/l+jR7MZp8Ks0f1aDkX9DS4ry/gUnY2dMqX0UovzpsqK/WuMbJcX7n0LZXY+cb5HS4XJFDMSKKFkxWT/AlbvHxq7bjh88U7dmeAKcf29WURbYSYBFhmE5PoC0waEPxygU78hzr9xvplVU6PrLBG/0mnB0envahVlPPRJKVTOlY3DA5B77ER3xj+D3JOZtIdvvHLmMeK/SV6zCwdXuKjmOFtXu6qbw0LaYR5lZYgfVnRJIVF5iEzmfQ7sGdM7mf5D66pL+SSFf43lDnGa1PJRT/kBeVR1cZPOdU7m5mu2Q4Nkt2B2sjISX7l5ayblOpx3yHReaGhkT6pv0oqRb307uI2Rr8D2nIeG7UoDWe8Y0VIDRTj7Qq+bI2hSVK5F7Geqkq6TY8MTmaw6pKx/iyt6xWg015G78bgDZf6pmX35tDXKobNTla8zZ25Tijuceir5a5d91L4B24QS+k/xV8VCyp/0SUDkxGtEAEfeMMJ3KSRV8uM2/Y2LniVsYXH3UsoDnrEemATPJ3if+wHGalMGY0OOUX5kwGCwACBhfiDkmAzMxEekQGX1sFSHa/SLEo7Hg3regzINZtO4wy7XiJCMS36G6YSNUrBUOU/yL7I6eLZp4lgQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: web4-secret
      namespace: cwx
    type: Opaque
