---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: aliyun-dns-secret
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgBD1FH55Zz8sFcPRTb+bQlfHQi8/1D26fkGS2kSQXPxFgF4Jmjf4rp1+BJx34iFB/Y1ywjMAIkUR+fw/zKX7JfhhRJzagnWl9BNlIl2+mHmDb0IsS1ZJmSBbdQUweapIec8I0S00RekDnJNYVf20yKf9eN+RjY+jG+zvrVUL6m2qQfxbnjP6nROeym7O6kKVcWUCa5PbCvSXmWMWbW2TkZi+CWUrYEanusSsV+TPmMsxlyBco5wRtc+xLbOWtvlru2y+iumro/7bbdXJ5chwwoS3rXDh8ueoMKInC8v0rp5etnIj/WdeqvQ5kXV83hsVjJcBd7RjLNSbAY5ZXhgZkZTnUaIUo6PT8I3IDiZ+yWk37oWXbasnTG6JpOaJrtwhHCj1sGLXN9LPcbAzoR0YAcrNECi27ie4Tr+LWwrGqctVvvFIoAKZ6gHY1frNG/9nBDqSlhSpvqqoTawF75WPOkZYx07xIsU0/cu8v+TbOW+7W8272r4gJtBOWC0g12zeVBIldRp4HiFZIxriLMiV05j9kVcLZ3a2FTdeK5gxZhov8FTu+wedQtZLwkaiWMyLEREzgymQJ9NhaZqorDo/trHBVJ7x2ZyNmYjgBHifJF/Z9JjG371gqPO16iYKMe16l1Tc9QHYu6pIoPwx/Jh8qeZK2JxJquTZaloY+PsoPztOk0dE9FqS00I0ZYELcXyfeOZx2nHxxWI2c5OjDDy+Mdvn/bgMKBbT9Q=
    access-key-secret: AgBqwoZLpsxJi4P0QCiirdOHbdjijAtAvcIW4QDF/j3VA2huk7/f+owYRMuLCEKgrxbfS4KW+5VgjbsEW/WJuAjLps3Fp9tzGxwbNCnZ9W+UF4B1O1qVJrmgKe0slRXjoOr2pKUekXCMKg1oWY+BD9lJItZ4f+GyzwB/68nmRZXDxPf4B/SzMr4oLnizAkbaYRPaMBlRS7HbbVVkar6s6RuTywipApK52MxO2DPAZrfMWqE34X64a2QD/KDunJOxTlXkvh53xf2ciwbT/VkxL9DN2l3zArGHS3UYtvKwxGvUxoaOQtQUcBNQGemcozImUtgJ7X3Zx77ybMbcgA1FLjhc8MrkTYumE8azGac6xzuoUKhPwG3dYmUIeL+DRxiRQTYN+T8MdA3fDjnzWxuP/hQRKjUqNA0Y/iruvr7TX6jAzjCPr27gDMoeUPmJ4RvapAGcYeDunJD+CjrVH3pftz7BvD/NKkgwBMNne/SpxhNy98bCHSNQI0ky7NGYb/qDygCUq4SE2M9p+v0ZE5ueqer6+SSGiEAxCMmIXbsR3YVv+TBnAExJJcHVwjLxG0CkrRB+S8LG8ol+D9IPdSst4gMUMwzeDdiQmfvTJHlxkWXCzdB7y7zY4RX21dXLLkWuk/J0jQ+erINXEkO33sDaDqaCRnWiRlQWm0XshUc6PwJlL53hrTAjZfn+NCWs6R92o5jBFRdwEhvsnucVqpGxgfdB4xX2BvW6eq/k2AAHcgI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: aliyun-dns-secret
      namespace: cert-manager
    type: Opaque
