apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: opensearch
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Prometheus
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch.monitoring.svc.cluster.local:9200
    isDefault: false
    jsonData:
      database: otel-logs-*
      flavor: opensearch
      logLevelField: severity.text.keyword
      logMessageField: body
      pplEnabled: true
      timeField: observedTimestamp
      version: 3.5.0
