apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      timeInterval: 30s
