---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: harbor-registry-chenwx-secret
  namespace: cwx
spec:
  encryptedData:
    .dockerconfigjson: AgBW1xlEBT2rglNDiWL8no02nQ0HPgZVJinkMSy2HLs+YNxNT/HgXaXq6M32EtwlUNbb57UxsTVhdiBKAMD2p0WIwtBlHkSzoGUkwim0ib+vXtdEqr0CCHxCw6aZDpZzfjNE9O9GFMnI0yTQUjhrXNuGXTfctuLyWoeebfd5v477t66ml3cwY0JkKuPlCNa1uF6oQSj0XWnLXedfX1M+CddbBr9RiUDL6E4J4ktzGFmKBXwTFweVIGhbWOshOrqEo0dVPESAHkBksjzyEQY+6KpNZ46MirRQmZfg2FstilEU/3eHFXDmrLbeaRaF/Hx/qjM88sPhKs13ppuck4yTPsYVaWlZVf+qEGZ3EJvDndk4mxyLtACK5C4XFYJZEDXeEvPjaPTDI9iAJcG+r9GkTxk5nfDRjZNCOB6ES3SUow8IDf0ilPx7eOX85S0H78QlY1KO5ktVyWMmuh3Rzvd95YjCTWQuAVgnuJPA14citr4L80TIUhp1/vDVMxI7wc0D+tkojABRIGpi/Ycc4sbnQGclka09+uRS6ptNFVDAiezs+DMicbaP6jbJ8GfVTmIWWCqsYCfhV1AVf8ZduyMgopO9X1/sSmoPHpLLWNai2Ikcvk9Xo3qK/GtBEj1OunDIDkfPNEumhCmyL8ugcbKz8Whc6IEqZRhk3LiTMY1WT/SlEEZo9c+L7FSzLfRVv3hpZj9LAZkEbTjZhtWEaYdHoUHl7D3fzF3K7+mJGjMM0qTddvQe5FQbtJa0GIqs39WrpFx+rRGYj5tvkFe+d5Fck13vIrFLA/Gag4EYsyx0ex6lYGDwL2lN5ppqvEFro67VHq3UsAlUVm1m0w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: harbor-registry-chenwx-secret
      namespace: cwx
    type: kubernetes.io/dockerconfigjson
