networks:
  core:
    external: true

volumes:
  jaeger:
    name: jaeger

services:
  jaeger:
    user: "0:0"
    restart: unless-stopped
    image: harbor.chenwx.top/docker.io/jaegertracing/jaeger:2.18.0
    container_name: jaeger
    networks:
      - core
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./jaeger-config.yaml:/etc/jaeger/jaeger-config.yaml
      - jaeger:/data
    command:
      - "--config"
      - "/etc/jaeger/jaeger-config.yaml"

    labels:
      - "service_name=jaeger2"
      - "traefik.enable=true"

      - "traefik.http.routers.jaeger2.entrypoints=https"
      - "traefik.http.routers.jaeger2.service=jaeger2"
      - "traefik.http.routers.jaeger2.rule=Host(`jaeger2.chenwx.top`)"
      - "traefik.http.routers.jaeger2.tls=true"
      - "traefik.http.services.jaeger2.loadbalancer.server.port=16686"
