
service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    storage:
      traces: some_store
      traces_archive: another_store

  # 定义数据存储后端的细节
  jaeger_storage:
    backends:
      some_store:
        badger:
          directories:
            keys: "/data/jaeger/"
            values: "/data/jaeger/"
          ephemeral: false
          ttl:
            spans: 168h   # 7d
          metrics_update_interval: ${env:BADGER_METRICS_UPDATE_INTERVAL:-10s}
      another_store:
        badger:
          directories:
            keys: "/data/jaeger_archive/"
            values: "/data/jaeger_archive/"
          ephemeral: false
          ttl:
            spans: 168h
          metrics_update_interval: ${env:BADGER_METRICS_UPDATE_INTERVAL:-10s}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_store
