---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: kite-secret
  namespace: cwx
spec:
  encryptedData:
    superuser-password: AgA9i/cp+EcqBCj58gO+tFtCLa4uWNwNtMLDm/7rCqiCA/1tuTCYrhXO/fNRKALoMck3XEwHWyXQ+tmeFn1vIfHrQw73cIC+TON9DswfojimDKJfvqJhXqwnoPixhzSgXTHuY72eCN9adtYlof0Gc75Lls0711GF8QIVSfx3dQsqlP6ET+GpclgXAdi9faHdaBdrrBYeJgv34mjY+ZW1mU3wPvevCTexPESuUBmT+9D+bpLN6Ueg23WJsw8BP0x4ltZPJvfeGK/VenRv+0Jk8pnerZUFW3h1RnHtanTT2sCqM9UZaADh6HZEOUhF5YdJWav+djSmI++RHNIvuf296Zej8+qEl0hbiNqxxYQOHX6e8owZxBc3+8qpyU0LOcPF6QxtvgyAgvlPFkZYtuBrarxQNq1T4As/085NfajopzXD+dcztnLxKBJ431nS8ahk5F8jaJn6PZLJcNgiju+BidokkyXKyrOyvTDqWL1P+GBJBx5r4lXJ/jBxmT5aGpI5ER4vV76rWoy0z770Zys4AqFel2wQeyBENiGdEpwFc1VdHqpq0RBVcnrCzhVqqSOJgD9TZKHnxFlb2EKiRUW8p0WEIfDAIdUNb9gWV612vDZJwMSGxhaTZ5PewHZN3ikCqN9fU7ZAZBzkCnDcuOs2p8ECF7Kqk2lUaw5zl6EBoZmV0XJleZ5WGegZ/DpsG5F4w2nDyVQjI4eTrw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: kite-secret
      namespace: cwx
    type: Opaque
