apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - class.yaml
  - rbac.yaml
  - deployment.yaml

patches:
- path: patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nfs-client-provisioner

- patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs-client
    reclaimPolicy: Retain
    allowVolumeExpansion: true                # pvc 是否允许扩容
    volumeBindingMode: WaitForFirstConsumer   # 存储卷绑定策略

- target:
    kind: StorageClass
    name: nfs-client
  patch: |-
    - op: replace
      path: /metadata/name
      value: nfs-home-sc
