apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-agent
  namespace: monitoring
spec:
  mode: daemonset

  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0

  # 添加主机路径挂载
  volumes:
    - name: varlogcontainers
      hostPath:
        path: /var/log/pods
        # type: DirectoryOrCreate
    - name: varlogsyslog
      hostPath:
        path: /var/log/syslog
        # type: FileOrCreate
    - name: var-lib-otelcol
      hostPath:
        path: /var/lib/otelcol
        type: DirectoryOrCreate
    - name: hostfs
      hostPath:
        path: /

  volumeMounts:
    - name: varlogcontainers
      mountPath: /var/log/pods
      readOnly: true
    - name: varlogsyslog
      mountPath: /var/log/syslog
      readOnly: true
    - name: var-lib-otelcol
      mountPath: /var/lib/otelcol
    - name: hostfs
      mountPath: /hostfs
      readOnly: true

  env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "host.name=$(NODE_NAME),host.type=k8s-node"

  config:
    extensions:
      file_storage:
        directory: /var/lib/otelcol/storage
        create_directory: true

    receivers:

      hostmetrics:
        collection_interval: 10s
        root_path: /hostfs
        scrapers:
          cpu: {}
          disk: {}
          load: {}
          memory: {}
          network: {}
          paging: {}
          filesystem:
            include_fs_types:
              match_type: strict        # 匹配类型
              fs_types: [ext4, xfs]     # 限制文件系统类型


      filelog/pod:
        include:
          - /var/log/pods/**/*.log

        exclude:
          # 排除 opentelemetry 命名空间下所有 Collector 的日志
          - /var/log/pods/opentelemetry_*/*/*.log
          - /var/log/pods/cwx_web6_*/*/*.log

        include_file_path: true
        start_at: end
        storage: file_storage

        operators:

          # # 从路径提取所有 k8s 元数据
          # - id: extract_k8s_metadata
          #   type: regex_parser
          #   regex: '^/var/log/pods/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[^/]+)/(?P<container_name>[^/]+)/'
          #   parse_from: attributes["log.file.path"]

          # # 添加到 resource attributes
          # - id: add_namespace
          #   type: add
          #   field: resource["k8s.namespace.name"]
          #   value: EXPR(attributes["namespace"])

          # - id: add_pod_name
          #   type: add
          #   field: resource["k8s.pod.name"]
          #   value: EXPR(attributes["pod_name"])

          # - id: add_container
          #   type: add
          #   field: resource["k8s.container.name"]
          #   value: EXPR(attributes["container_name"])


          # 1. 首先用正则表达式从文件路径提取 uid
          - id: parse_k8s_path
            type: regex_parser
            regex: '^/var/log/pods/[^_]+_[^_]+_(?P<uid>[^/]+)/'
            parse_from: attributes["log.file.path"]

          # 2. 使用 add 操作，将 uid 添加到 resource 的 attributes
          - id: add_pod_uid_to_resource
            type: add
            field: resource["k8s.pod.uid"]    # 注意：resource["key"] 语法
            value: EXPR(attributes["uid"])

          - id: add_log_type_pod
            type: add
            field: attributes.log_type
            value: pod


      filelog/system:
        include:
          - /var/log/syslog   # Ubuntu/Debian
          # - /var/log/messages  # CentOS/RHEL
        start_at: end
        storage: file_storage

        operators:
          - id: add_log_type_host
            type: add
            field: attributes.log_type
            value: host
          # # 添加主机名
          # - id: add_hostname_from_env
          #   type: add
          #   field: attributes.host.name
          #   value: EXPR(env("NODE_NAME"))


    processors:
      # 只做基础的内存限制, 不做过重处理
      memory_limiter:
        check_interval: 5s
        limit_mib: 256
      batch:
        timeout: 2s
        send_batch_size: 256
        send_batch_max_size: 512

      resourcedetection:
        detectors: [env]
        timeout: 5s

    exporters:
      # 转发到中央 Collector
      otlp_grpc/pod:
        endpoint: "collector-gateway-collector:4317"
        tls:
          insecure: true
        compression: gzip

      otlp_grpc/host:
        endpoint: "collector-gateway-collector:14317"
        tls:
          insecure: true
        compression: gzip

      debug:
        verbosity: detailed
        sampling_initial: 2
        sampling_thereafter: 10

      debug/java:
        verbosity: detailed

    service:
      extensions: [file_storage]
      pipelines:

        logs/pod:
          receivers: [filelog/pod]
          processors: [memory_limiter, batch]
          exporters: [otlp_grpc/pod]

        logs/host:
          receivers: [filelog/system]
          processors: [memory_limiter, resourcedetection, batch]
          exporters: [otlp_grpc/host]

        metrics/hostmetrics:
          receivers: [hostmetrics]
          processors: [resourcedetection, batch]
          exporters: [otlp_grpc/pod]
