---

- name: 配置内核模块自动加载
  copy:
    dest: /etc/modules-load.d/k8s-module.conf
    content: |
      overlay
      br_netfilter
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack
      ip_tables
    owner: root
    group: root
    mode: '0644'
  register: modules_config

- name: 立即加载内核模块
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack
    - ip_tables

- name: 配置 K8s 所需的 sysctl 参数
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }


- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: true

- name: 配置 NTP 服务
  ansible.builtin.include_tasks: ntp.yaml
