apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  selector:
    app: postgres-exporter
  ports:
  - port: 80
    targetPort: 9187
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: harbor.chenwx.top/docker.io/prometheuscommunity/postgres-exporter:v0.19.1
        args:
          - "--config.file=/etc/pg_conf.yml"
        ports:
        - name: http
          containerPort: 9187
          protocol: TCP
        resources: {}

        volumeMounts:
        - name: config
          mountPath: "/etc/pg_conf.yml"
          subPath: "pg_conf.yml"
          readOnly: true

      volumes:
      - name: config
        secret:
          secretName: exporter-secret
          items:
          - key: pg_conf.yml
            path: pg_conf.yml
