networks:
  core:
    external: true

services:
  dufs:
    image: sigoden/dufs:v0.45.0
    networks:
      - core
    # ports:
    # - 3010:5000
    volumes:
    - /data/share/tmp:/data
    command: /data -A

    labels:
      - "service_name=dufs"
      - "traefik.enable=true"
      - "traefik.http.routers.dufsHttps.entrypoints=https"
      - "traefik.http.routers.dufsHttps.service=dufsWeb"
      - "traefik.http.routers.dufsHttps.rule=Host(`dufs.chenwx.top`)"
      - "traefik.http.routers.dufsHttps.tls=true"
      - "traefik.http.services.dufsWeb.loadbalancer.server.port=5000"
