load_module modules/ngx_otel_module.so;

worker_processes  1;
error_log  /dev/stderr  notice;

events {
    worker_connections  256;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    server_names_hash_bucket_size 64;

    otel_exporter {
        endpoint    jaeger:4317;
        # endpoint    jaeger-grpc.services.wait:4317;

        interval    5s;                    # 批量发送间隔
        batch_size  512;                   # 每批最大 span 数
        batch_count 4;                     # 最大并发批次数
    }

    otel_service_name "homeLab-nginx";
    otel_resource_attr "deployment.environment" "local";
    otel_resource_attr "nginx.version" "1.29.8";
    otel_trace on;
    otel_trace_context propagate;

    log_format  main '$hostname:$server_port:$msec:$connection:$connection_requests '
            '$request_id '
            '[$time_iso8601] $status $request_time $bytes_sent $body_bytes_sent '
            '"$remote_addr" "$http_x_forwarded_for" '
            '"$upstream_addr" "$upstream_status" "$upstream_response_time" '
            '$request_length "$content_length" "$host" "$http_host" '
            '"$server_protocol" "$request_method" "$request_uri" "$http_referer" '
            '"$http_content_type" "$http_user_agent" "$request_body"';




    # access_log  logs/access.log  main;
    access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen 80;

        # root /data;

        location / {
            root /data/blog;
            index index.html;
        }

        location ^~ /tools/ {
            root /data;
            index index.html;

            try_files $uri @route;
        }

        location @route {
            rewrite ^.*$ /tools/index.html last;
        }

        location = /health {
            access_log off;
            return 200 "ok";
        }


        location ^~ /files/ {
            root /data;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        location = /files/ {
            root /data;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
            sub_filter '<a href="../">../</a>' '';
        }

        error_page 404 /404.html;
    }
}
