---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: loki-s3-credentials
  namespace: monitoring
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgARZzVSunAkegOW7HlSr7Q+DN3559z2uuvK5hi8qlImYcFiizOvtUm8dtfRgKgzic1ZKCoTsetHSXCY/c2LLCMDMCiZmWIL7ioxrkr5MeIs6lmrtYeoR5mEFYSdU3kJ3Eb3J2Y5hGWneMJi4DgukGsEKyRStxwwFAzdMfeOotX6sZ8HxNC6lSoxE2VIB17ovYZqVaXogVJ8qzUDVfpgcYoFliOzhkwoZo4eCBYVXJYzFh/f57RC9fRg2PmHQBUNJi0cLfhGD9w6PDk6GUh74jcuPu7jmg3W7Og31aZhjeTSclz2SSt8/uKh79r/QU5her/r9l9JiCT6yuhvd39AckjzA8CglvQrCk/C40oCHwfRJGCvWBYpglLRF2t0n0mq6p5h5fLcdcZmrF1Igv9f6g25MrsKDupLhvA3pb8Uxbfpl4NuitAntvp9Ax/eriEURrgzj7eIjnXJ9C3SEtzTJ1zZ6iZ8DBf91pySH7Avh4CmmmZPNY9z02WRwq4Pa3N6F4T5D1n98iC0swELrNMyD8Y6n+tRQaBIlGIa+t9igznQuiBNwx9erEn759+57Z8R1vygeuzDMsOknu5chSMgDw6quKnQCkLLNrdTL/nKM74tiLBDH5jGdQWqpYnWipt36Q2Cswkmg7AfjzhLZy8gPSy8An7DOsBOmx7cb3x2EFJPa1YOCYq/Eedd08LJiVx0FUxNhdUjkADsOAy3J7bdBsi/4HWOhg==
    S3_SECRET_ACCESS_KEY: AgAmP+WHkoazN0IPjeHjGOnNiQg6JzDvqkwTN3F6ovJLI1cZNSfiYaPgD6JYVMTZpDc3gmGR7RWppgoW5s+Roea5zVcdynYUOv5MsbDiim3IJrZpIVMJgUeO1XgN2fyHje50QVecywSQCTEoaPRov6Fzd/y1+MZZGQ2MTwnEkYSx0umjTTkgGYd9rSxd0kQaylYHppT8aprmT4fiHbGcUtDQycZR+yLyKTfD63jW1v6ALpOvOKcABpM4QZVnQIoBqTuUFRF1nCRleUq9q1gp1rB3X3DePdzEfuv9QJucv4eJX+gKtYJtOf+ECg4KpBx58jufgGDeSulQFMR7djIB9OegkfNMtanmNwT+y0We2YdEdnBJ9zIK1JiZqK/RxKxiMUetkMTNupJkG7rbPzhUGL6mN/CMhbqjWBcsgbpCQ0RoDqGFTRjpRmIi8h0MhV7d/Yn2/QedPpq3KN5pYwB3BGUBKEc0a5temEYz4EFnOVT3V58HMrOdDBoA5L9aT8ifWPasRcX01zhCpUsjmgos5ZzR1aupxGvfZZXI1K8+k+l3eVki2Azqfy1/iEkGH+2VC9NeEG6nqBfaJ9yWAct33Pyi76s10Wt4PI2PoK8Scss6IHqbhGZyKkyFCT327cz/UCnUVyFkKpx20yQ/yenyl0t2BN8HssUb+WELDMZpXePjdiFmBGTwbsiQJsduYyf8usUgXxlCnddUKoi1Z18VN91VSSn7vYgUIoIf3XG331GL8UXsAAIPV59R
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: loki-s3-credentials
      namespace: monitoring
    type: Opaque
