worker_processes  1;
error_log  /dev/stderr  notice;

events {
    worker_connections  256;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    server_names_hash_bucket_size 64;

    log_format  main '$hostname:$server_port:$msec:$connection:$connection_requests '
            '$request_id '
            '[$time_iso8601] $status $request_time $bytes_sent $body_bytes_sent '
            '"$remote_addr" "$http_x_forwarded_for" '
            '"$upstream_addr" "$upstream_status" "$upstream_response_time" '
            '$request_length "$content_length" "$host" "$http_host" '
            '"$server_protocol" "$request_method" "$request_uri" "$http_referer" '
            '"$http_content_type" "$http_user_agent" "$request_body"';


    # access_log  logs/access.log  main;
    access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name docs.services.wait;

        location / {
            root /data/docs/;
            index index.html;
        }

        error_page 404 /404.html;
    }


}
