---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: nacos-secret
  namespace: cwx
spec:
  encryptedData:
    MYSQL_SERVICE_PASSWORD: AgBGDGjya4GTAlK1HtxheVJxlssO9wuuFtMfX2sjcnbCLN9kPRi7GC7dZOVHcCeFNogOc8M4mp2Wz4F8boRPKuC7SNmiTUqPMIJPkwksARg/y1K+cM71uXxZsL78x0r2Ky1Ch0gAwVshy/deMSCP9xK7u1N+6NA++zRqJA+atugj/j/IG2y49Qm8YoHMJTun8yCFbopPTjZ48AXsynjmZGWFyiz6J6RItS6/Ion+gEuSZD25rLAKjGBPqC4UiXiblIi12Q2NfEmnyUZ4J+htHE5ChIsTXdhGytIEnbvx/i4lPiHgNkoNEF/wqLqeK0a/Gbz5HLxkdhKV4/A6OIi54nvA8egiCtSLdH0uAjQemLzDpR0Qm60wADSVKu5N1He4liJcL80x/945mvAuyVWxapRqdNhjqJPFlf9X3f3bSWtgCm+6n2n73bUYMvjqsR5EJqivbgGtG8Uf5BokVPhJFBZWU5yADOgGatEpNHXD5teKVFH8r3508JVVVz8ttri0t6RwQeVjWdXTjAxkdteovYyjc/n/w7Bs20DJFX16FyvPGBSxn3sb+Df4YtkR9ApxdIe4CQnsFY3DYQJ3EIcK7hGbRU0/5n6E14vTV32S7Y5cEtMgthuBxfwyMwPqOJvuPDFWczetxrBCUNE7TiiN78LrLtr7kSHIWll9wFRPHCwd2NmXISj4U8rLCkW9yYRkQEuf7TK0CizLyQ==
    MYSQL_SERVICE_USER: AgAb8I+ARRJ3gaKPHn6wzNWgpv9Onke0drXhMwaWa5jFWEO/YKTB2M+oxgCuqJFzhhaBtwHPlYyC46d74pe7O/bI/KECA4blerqPnnQ9eRlaFLnV3WbLJpw3LDVy9halvEGYmSJrQ3tdcLBi0jKtjXv7Vgr7qd3Wz4wKF+9r1fW6K4bsAdrLX3U+/erRg5blsgEI6a20XNOZW5vZ/vUiusSSaN6ptj+fPENebEV8Uo0LktM9kdEYWIfzZGEnvaBRTiG6ssdspd/2LcHdDY/k80HcezSLCuXEf1YupMFTpqIxVjQJ36+YZUDEVMLmzyao64IyQ8J5jDQOuautM80ArK8OkjUOXstOp7fhHVXMP096en9UZmN3auiI12gEraO1Mb0HekCMtdSDCqFW9IMdnXKwh33SErMc7pUsdHa3COUexMnnyGDoHYArsH5LJQ2h9CjMyHWV5qzmdT7DOhnQ0TugMfE+9KPamauE0+00WyX0jhTuO9q8wuNC6mI7kEn+NQa8n2jmXpiATK3fP4MYuCFV+sSqoMyumc6LeGBzokJeC0jmIzuvCJmOI/Mjwqoe2oUb0+XyisTFvEXjyD1wCCAis27Ho1I/y7nMmdmhgKzfJtPX4Viip+/1Bt/szLH7BK2TFrqdoKm1VZZUKVQniBbUMs+B37cSUS9MvMF3kSH9tphEqU4RdpiPEsVSgnY10F1eIOlN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: nacos-secret
      namespace: cwx
    type: Opaque
