{
 "title": "[Image-Provider] NGINX Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Accepted connections",
   "type": "stat",
   "description": "total accepted client connections",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "conneNumber/min",
   "type": "stat",
   "description": "每分钟新增连接数",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections handled",
   "type": "stat",
   "description": "The total number of handled connections",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Total number of client requests",
   "type": "stat",
   "description": "The total number of client requests",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Number of connections by state",
   "type": "timeseries",
   "description": "The current number of nginx connections by state",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 4 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{state}}" }
   ]
  }
 ]
}