apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: higress
    repo: https://higress.io/helm-charts
    version: 2.2.0
    namespace: higress-system
    releaseName: higress
    includeCRDs: true
    valuesFile: values.yaml
