apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    # repo: https://traefik.github.io/charts
    repo: oci://harbor.chenwx.top/public
    version: 39.0.7
    namespace: cwx
    releaseName: traefik
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - TLSOption.yml
