---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgCFEEhaGn2/EwJlvoRfzwnbGsPl6pXY3xjeCziekQZdKjip8tRSugTy8p+HRDys184TZnhfJTQ3bJZlxXuZ4nIWvo3e7ZtAIpluP/7q09uDJXyV24cOiQgMVJrlPMdxMmQG5Ilo+FQvdXtOk8oX5sOgCMkQNgQvxUbxhCn3KGZ72Qv6K1HO5WoMZVAAryC6xiqaN4m4WQGzGsI+U63PAReprTLQLWmCXX94l7SqjtWJn5qIekCkl36/ilAERPYwAJojo9/MZK+n8eP3qo0WpELIdoNMQxlYB2t7hZhaNEypvWPTbVoG+gXIJur/8SubtF3UIjkvpJPgtJo4BJ6Ao4Y1FzIHiiB2RAaBJlDEq8yC6K+3ulOXxCGgVYX64UmjUfa6+chn5gfMd3T0egrlDOYpZN438UMG577w7SlvB/bHcYQ6/4e+WMBbUjp6MnVWObkZArcivq1SUekqKFoJIBMlHIpIOuK2gNYH19Hz0nGsmW5EV+2ZgOxnzvkuexHwgC4uyDJLY3iIG+cI49xkCJn3MAqgk25Slq78wptnhE0TPiW946SHCdlhgr/Hu0kr+6aZPV1NawgtUReoyziqgqrehxeqC00QJ2wRctr1hwu1okAfBJi145khMKylEMYEgmnFQ4eOHZrK+bp3/NBYPQfPtWKruDSQjSWb7b/SbPhSfWFNJVJY041Z8MjQxpQCYYZsHZ6PLR7xAA==
    username: AgBuFXxkyCarlgxMRGCVlcU0CvTfwo+HB2dproRyy4LYVGpEIwtVoDuhcTKssyiLU8f7poCZ6/kPCQ0+AaD5z40t3aJm1acWurpzaBnZWHmvh0rYeeEuu7TBPZ+ffFd16v/8vG6CKISbR34yBXuI1ZhLwPkiTHWuLQpV+pK0ndFH5CaHNAxyF4YCSrn01qMiDvO1zcpQwoWk4a7S3AEqmzkuKoiYtpBF6bky1pdH3Bqe1x7xOlqFAJBIjQpBQQ9NJWAjqqiayG0VbDzyYmeEMDQ0bGgNjYdZFExkxbrQ0OTSZbWMrdLrvAQnBzD5T+nOPYO1bl8I7YCKq6EbzA7DvQCM6Nc5X34U7ch8+PTKTR3xr7AikqemH5tOwT+iyQi2W3nyPZkCuwEHUiI1mP9ZQ2EgDnXl0zePyfQOJNzeSBjYc0HqJXd0P1RFZJKcYSNiY+nvbhSUukVdLaLZTgRwY6gwqRwDfvoHABnWEG6Ep6zvdkfkwwAnPr81u5rabdaqSJVCf8p6R17IPoZaDxattEEo7x410tAUnMTe9FTqM4eYMSUeNbuHR4UzMdaTitzhxpbrP+BT/KLeu7y5xSlCZ4doMKaGxgxLGnPpG3en78FiZji7767ZNgAselrh/LircUQ7mSh16/uonhsE1pzkj93Zs3d0cVfgSYdqzT5O6W5GRl1u1DVmotRmSQCWeCN/vwY/TPdafA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-secret
      namespace: monitoring
    type: Opaque
