
# /etc/smartdns/smartdns.conf
#===================================================================
bind :53

# server 223.5.5.5 -group china -exclude-default-group
# server 223.6.6.6 -group china -exclude-default-group

server 8.8.8.8
server 1.1.1.1
server 202.96.128.166:53

rr-ttl-min 60
local-ttl 10

#===================================================================
# 开启日志
audit-enable yes
audit-num 16
audit-size 50M
audit-file-mode 0644
audit-file /var/log/smartdns/smartdns-audit.log
# audit-file /dev/stdout

#===================================================================

# 全局禁止解析 ipv6
force-AAAA-SOA yes

# 屏蔽策略
# address /zijieapi.com/#

#===================================================================

address /crash.chenwx.top/192.168.5.9
address /anythingllm.chenwx.top/192.168.5.9
address /dufs.chenwx.top/192.168.5.9
address /jaeger2.chenwx.top/192.168.5.9
address /dufs.chenwx.top/192.168.5.9
address /traefix-09.chenwx.top/192.168.5.9
address /files.chenwx.top/192.168.5.9
address /vault.chenwx.top/192.168.5.9
address /miniowebconsole.chenwx.top/192.168.5.9
address /minio.chenwx.top/192.168.5.9
address /victorialogs.chenwx.top/192.168.5.9
address /harbor.chenwx.top/192.168.5.9
address /git.chenwx.top/192.168.5.9
address /higress.chenwx.top/192.168.5.31



# 放行到上游去解析
address /www.chenwx.top/-
address /blog.chenwx.top/-
address /docs.chenwx.top/-

# 二级域名规则匹配冲突, 单独指定
address /chenwx.top./8.141.8.99

# 其它地址去集群网关
address /*.chenwx.top/192.168.5.30

#===================================================================
# 指定域名到指定上游进行解析
# nameserver /xxxxx.local/office
